version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./etc/Dockerfile
      args:
        ENV: production
    image: backend_meta_django
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    command: /bin/sh -c "python manage.py collectstatic --noinput && python manage.py migrate && uwsgi --ini uwsgi.ini"

  postgres:
    image: postgres:11-alpine
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:6.2-alpine
    volumes:
      - local_redis_data:/data

  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"

  celeryworker:
    <<: *django
    container_name: celeryworker
    depends_on:
      - redis
    ports: [ ]
    command: celery -A config.celery worker -l INFO

  celerybeat:
    <<: *django
    container_name: celerybeat
    depends_on:
      - redis
    ports: [ ]
    command: celery -A config.celery beat -l INFO

